default: &default
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: coreydavis1
  password: 1234
  host: localhost

development:
  <<: *default
  database: ck_cms_development

test:
  <<: *default
  database: ck_cms_test

production:
  <<: *default
  database: ck_cms_prod
  username: <%= ENV["PROD_DB_USERNAME"] %>
  password: <%= ENV["PROD_DB_PASSWORD"] %>
